plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}



dependencies {
    //testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    api 'org.jocl:jocl:2.0.0'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

